name: Run Crawler

on:
  schedule:
    - cron: "0 */6 * * *"  # Runs every 6 hours
  workflow_dispatch:

jobs:
  deploy:
    name: Update Algolia Index
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: website
        shell: bash

    steps:
      # Checkout the code
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Check invalid redirect rules
        run: |
          incorrect_paths="$(jq -r '.redirects[] | select(.source == .destination) | .source' vercel.json)"
          if [[ -n $incorrect_paths ]]; then
            echo "There are redirect rules with source = destination. Please correct them." >&2
            echo "$incorrect_paths" >&2
            exit 1
          fi

          repeated_sources="$(jq -r '.redirects[].source' vercel.json | sort | uniq --count --repeated)"
          if [[ -n $repeated_sources ]]; then
            echo "There are repeated sources in redirect rules. Please correct them." >&2
            echo "$repeated_sources" >&2
            exit 1
          fi

      - name: Trigger Algolia Crawler
        run: |
          curl -X POST 'https://crawler.algolia.com/api/1/crawlers/8b786e95-d4a9-4229-a89b-d7bb66/reindex' \
          -H 'Content-Type: application/json' \
          -H 'X-Algolia-API-Key: ${{ secrets.ALGOLIA_CRAWLER_API_KEY }}' \
          -H 'X-Algolia-Application-Id: ${{ secrets.ALGOLIA_APPLICATION_ID }}'
